### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by Gabb-c** [MenuDocs/erela.js#107]
There're a few outdated dependencies in this project:

![image](https://user-images.githubusercontent.com/65926741/114791857-94dd9100-9d5d-11eb-8bdc-aa2fa86f91fd.png)

It could be fixed by adding Dependabot to the repository. Few steps are needed:

----

 - Access [Dependabot](https://app.dependabot.com);
 - Link your Github account;
 - Select this project;
 - After linking your account, the app will ask for permissions to create issues, code, and pull-request’s.
 - Select the repository in which you want Dependabot to be monitoring for dependency updates.

----

Then add a `dependabot.yml` file in the `.github` folder:
```yml
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 10

```
